// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: accounts.sql

package database

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts ( id )
VALUES ( ? )
RETURNING id, balance_dollars
`

func (q *Queries) CreateAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, id)
	var i Account
	err := row.Scan(&i.ID, &i.BalanceDollars)
	return i, err
}
