services:
  gateway:
    image:
      wipdev/moneygopher-gateway
    build:
      ./services/gateway
    ports:
      - "8080:8080"
    networks:
      - moneygopher

  transactions:
    image:
      wipdev/moneygopher-transactions
    build:
      ./services/transactions
    ports:
      - "8081:8081"
    networks:
      - moneygopher

  accounts:
    image:
      wipdev/moneygopher-accounts
    build:
      ./services/accounts
    ports:
      - "8082:8082"
    networks:
      - moneygopher

networks:
  moneygopher:
