services:
  gateway:
    image:
      wipdev/moneygopher-gateway
    build:
      ./services/gateway
    ports:
      - "8080:8080"
    networks:
      - moneygopher
    env_file:
        - ./.env

  transactions:
    image:
      wipdev/moneygopher-transactions
    build:
      ./services/transactions
    # ports:
    #   - "8081:8081"
    networks:
      - moneygopher
    env_file:
        - ./.env

  accounts:
    image:
      wipdev/moneygopher-accounts
    build:
      ./services/accounts
    # ports:
    #   - "8082:8082"
    networks:
      - moneygopher
    env_file:
        - ./.env

  otp:
    image:
      wipdev/moneygopher-otp
    build:
      ./services/otps
    # ports:
    #   - "8083:8083"
    networks:
      - moneygopher
    env_file:
        - ./.env

networks:
  moneygopher:
