// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: services/otps/otps.proto

package otps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateOtpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
}

func (x *GenerateOtpRequest) Reset() {
	*x = GenerateOtpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_otps_otps_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateOtpRequest) ProtoMessage() {}

func (x *GenerateOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_otps_otps_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateOtpRequest.ProtoReflect.Descriptor instead.
func (*GenerateOtpRequest) Descriptor() ([]byte, []int) {
	return file_services_otps_otps_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateOtpRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GenerateOtpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Otp string `protobuf:"bytes,1,opt,name=otp,proto3" json:"otp,omitempty"`
}

func (x *GenerateOtpResponse) Reset() {
	*x = GenerateOtpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_otps_otps_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateOtpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateOtpResponse) ProtoMessage() {}

func (x *GenerateOtpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_otps_otps_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateOtpResponse.ProtoReflect.Descriptor instead.
func (*GenerateOtpResponse) Descriptor() ([]byte, []int) {
	return file_services_otps_otps_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateOtpResponse) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type CheckOtpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Otp string `protobuf:"bytes,1,opt,name=otp,proto3" json:"otp,omitempty"`
}

func (x *CheckOtpRequest) Reset() {
	*x = CheckOtpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_otps_otps_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOtpRequest) ProtoMessage() {}

func (x *CheckOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_otps_otps_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOtpRequest.ProtoReflect.Descriptor instead.
func (*CheckOtpRequest) Descriptor() ([]byte, []int) {
	return file_services_otps_otps_proto_rawDescGZIP(), []int{2}
}

func (x *CheckOtpRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type CheckOtpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid bool `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
}

func (x *CheckOtpResponse) Reset() {
	*x = CheckOtpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_otps_otps_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckOtpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOtpResponse) ProtoMessage() {}

func (x *CheckOtpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_otps_otps_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOtpResponse.ProtoReflect.Descriptor instead.
func (*CheckOtpResponse) Descriptor() ([]byte, []int) {
	return file_services_otps_otps_proto_rawDescGZIP(), []int{3}
}

func (x *CheckOtpResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_services_otps_otps_proto protoreflect.FileDescriptor

var file_services_otps_otps_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6f, 0x74, 0x70, 0x73, 0x2f,
	0x6f, 0x74, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x12, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4f, 0x74, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x27,
	0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4f, 0x74, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x74, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6f, 0x74, 0x70, 0x22, 0x23, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x4f, 0x74, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x74,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x74, 0x70, 0x22, 0x2c, 0x0a, 0x10,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x74, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x32, 0x75, 0x0a, 0x04, 0x4f, 0x74,
	0x70, 0x73, 0x12, 0x3a, 0x0a, 0x0b, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4f, 0x74,
	0x70, 0x12, 0x13, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4f, 0x74, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x4f, 0x74, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31,
	0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x74, 0x70, 0x12, 0x10, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x4f, 0x74, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x4f, 0x74, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x77, 0x69, 0x70, 0x64, 0x65, 0x76, 0x2d, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x6d, 0x6f, 0x6e, 0x65,
	0x79, 0x67, 0x6f, 0x70, 0x68, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x6f, 0x74, 0x70, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_otps_otps_proto_rawDescOnce sync.Once
	file_services_otps_otps_proto_rawDescData = file_services_otps_otps_proto_rawDesc
)

func file_services_otps_otps_proto_rawDescGZIP() []byte {
	file_services_otps_otps_proto_rawDescOnce.Do(func() {
		file_services_otps_otps_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_otps_otps_proto_rawDescData)
	})
	return file_services_otps_otps_proto_rawDescData
}

var file_services_otps_otps_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_otps_otps_proto_goTypes = []interface{}{
	(*GenerateOtpRequest)(nil),  // 0: GenerateOtpRequest
	(*GenerateOtpResponse)(nil), // 1: GenerateOtpResponse
	(*CheckOtpRequest)(nil),     // 2: CheckOtpRequest
	(*CheckOtpResponse)(nil),    // 3: CheckOtpResponse
}
var file_services_otps_otps_proto_depIdxs = []int32{
	0, // 0: Otps.GenerateOtp:input_type -> GenerateOtpRequest
	2, // 1: Otps.CheckOtp:input_type -> CheckOtpRequest
	1, // 2: Otps.GenerateOtp:output_type -> GenerateOtpResponse
	3, // 3: Otps.CheckOtp:output_type -> CheckOtpResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_otps_otps_proto_init() }
func file_services_otps_otps_proto_init() {
	if File_services_otps_otps_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_otps_otps_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateOtpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_otps_otps_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateOtpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_otps_otps_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckOtpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_otps_otps_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckOtpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_otps_otps_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_otps_otps_proto_goTypes,
		DependencyIndexes: file_services_otps_otps_proto_depIdxs,
		MessageInfos:      file_services_otps_otps_proto_msgTypes,
	}.Build()
	File_services_otps_otps_proto = out.File
	file_services_otps_otps_proto_rawDesc = nil
	file_services_otps_otps_proto_goTypes = nil
	file_services_otps_otps_proto_depIdxs = nil
}
