name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run Revive Action by pulling pre-built image
        uses: docker://morphy/revive-action:v2

  # style:
  #   name: Style
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v4
  #
  #     - name: Set up Go
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: '1.22.1'
  #
  #     - name: Go Fmt
  #       run: test -z $(go fmt ./...)

  # tests:
  #   name: Tests
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v4
  #
  #     - name: Set up Go
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: '1.22.1'
  #
  #     - name: Go Test
  #       run: go test -cover ./...
  #
  #     - name: Install gosec
  #       run: go install github.com/securego/gosec/v2/cmd/gosec@latest
  #
  #     - name: Gosec
  #       run: gosec ./...
